Section/apievaluation
dpw901e17/report pull request #21
Opened 2017-11-07 08:55 UTC by TheVikingGent

2017-11-08 13:59 UTC, ClausWiingreen requested changes
Mange små fixes

Er personligt ikke så glad for din citations stil, men som Bent har sagt er det ikke nødvendigvis en dårlig måde at gøre det på.

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Yet, in recent years more empirical studies of languages have cropped up.
'Yet' antyder at du siger sidste sætning imod, hvilket du ikke gør

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +The authors of \cite{ray2014large} compared 17 languages by pulling code from 728 popular github repositories.
Personligt ville jeg have brugt citet her hvis man alligevel taler specifikt om forfatterne.
Og GitHub skal capitaleres på denne måde : GitHub

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Each language was profiled and compared by the amount of errors they resulted in, as well as the type of error.
Hvad er deres definition af en fejl, og hvordan målte de det. Hvordan de målte det er ekstra intressant fordi vi måske kan bruge det selv

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Such an approach was used in \cite{grill2012methods}\cite{beaton2008usability} to great effect, as the combined usage of methods was able to spot a larger amount of usability problems.
Du kan citere flere kilder i en cite. \cite{kilde1, kilde2}

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Thus, the group of methods presented here is heavily inspired by the field of \gls{HCI}.
is -> are

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Thus, the group of methods presented here is heavily inspired by the field of \gls{HCI}.
Er der nogen grund til at specificere at dette er en gruppe af metoder, tænker at "Methods presented here..." fungere lige så godt som "Thus, the group of methods presented here..."

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Evaluators facilitate test sessions, where participants are asked to perform the tasks using think-aloud protocol.
Sætningen er meget komplex. og der mangler the/a foran think-aloud protocol

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +As a session progresses the actions and comments of users are recorded and noted down by evaluators.
As a session progresses, 
^Mangler kommaet^

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Following a session, participants are often interviewed or answer a questionnaire to post-usage data.
What are the paticipants posting??
Mangler gather eller lign.

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +The collected data is then analyzed to find and rate usability problems.
Hvad menes med 'rate' det er ikke blever introduceret før

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Evaluating a programming language differs in that tasks can have wildly different solutions.
Det kan GUI også have; gemmer man ved at trykke på Floppy disk ikonet, eller File>Save, eller File>Save As.., eller File>Export..

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +There should also be accounted for learning required to understand a language.
Der er også en lærings process involveret i at lære at bruge programmer med GUI, plejer man at tage højde for det?

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +This means that a compiler may not be implemented, when there is a need to perform a user test.
GUI'en er også sjældent færdig når man tester usability, det begynder man allerede på ved prototype stadiet

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +This means that a compiler may not be implemented, when there is a need to perform a user test.
Ud over det så er andre programmer også meget iterative, se SCRUM

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Thus it could be switched out with a more structured analysis guideline, such as one focusing on \gls{API} evaluation.
Thus,
^mangler komma^

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +The new dimensions, as written directly in the paper, are given in \ref{tab:cogdims}.
..given in 3.1.
Mener du figur 3.1 section 3.1 eller table 3.1

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +These can be seen in \ref{tab:zibran}.
Still no idea that it is the table that you are refering to

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +In addition, each problem found is also coupled with a severity rating on a five-point likert scale\cite{wikiLikert}.
missing space before cite

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +\begin{table}[]
Forskellig tekst størrelser mellem de to tabeller

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +\begin{table}[]
Og der er stadig det der underlige extra mellemrum over højre textfelt

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +Here they categorized problems according to a subset of \cite{nielsen1995} usability heuristics applicable to \glspl{API}, Consistency \& Standards, Error Prevention, and Help \& Documentation.
Hører det evt til related works?

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +While \cite{de2009automatic} state that they pick these metrics as they require access to only the interface, it does not seem that Interaction Level can be meaningfully calculated without access to
states*

2017-11-08 13:59 UTC, ClausWiingreen commented on mainmatter/method_of_comparison/api_methods/index.tex
> +\item Interaction Level: Number of interactions + sum of strength of interactions
What does strength of interactions mean??

2017-11-09 10:12 UTC, NotKyloRen approved these changes
Looks Cheeki Breeki!

2017-11-09 10:31 UTC, ClausWiingreen approved these changes

2017-11-09 10:38 UTC, merged