Section/related work
dpw901e17/report pull request #8
Opened 2017-10-17 13:43 UTC by NotKyloRen

Please put my hard work on related work into master

2017-10-18 12:34 UTC, AlexanderBrandborg requested changes
Overall. Still needs some content and needs some better flow between papers.
Why am I introducing this paper now? How does it relate to what came before it?
- Remember to have every senetence on one line. Difficult to give precise reviews otherwise.
- glspl please, so instead of \gls{API}'s, \gls{API}.
- make GPGPU a glossary entry and not GP\gls{GPU}.
- pull it through a spellchecker
- say paper instead of article
- often says "how that" just say "how". "How that" is a bit too talkey.
- perhaps insert papers you haven't written about as todos.
- no "sammentrækninger". So it is instead of it's. Stuff like that.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +During the search of related works within this project it was discovered we were hardly the first once to wonder how graphics \gls{API}'s function. From these papers it was discovered that a \gls{GPU
A bit too informal with the 'we's and the storytelling.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +The second purpose for the \gls{GPU} is for rendering graphics, this is mostly used in video game software. The following sections will further explain the related works, and why they are relevant.
Det bliver vel også brugt til film og generel visualisering?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +The second purpose for the \gls{GPU} is for rendering graphics, this is mostly used in video game software. The following sections will further explain the related works, and why they are relevant.
Maybe bring this up before GPGPU. It is what the GPU is made for afterall.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +During the search of related works within this project it was discovered we were hardly the first once to wonder how graphics \gls{API}'s function. From these papers it was discovered that a \gls{GPU
You may be jumping ahead a bit. I'd rather you don't tell them what we figured out, and introduce terms like GPGPU as we go along.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +\subsection{GP\gls{GPU}}
Maybe have this be the last section? Not that it's an afterthought but it's the section related the least to our work.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Meaning the article claims that single-threaded applications are no longer good enough, and the industry should adapt to GP\gls{GPU} technology.
Terms like 'good enough' are rather vauge.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +One way of utilizing GP\gls{GPU} is through CUDA.
What is CUDA? A language? An Elephant?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +This article is relevant as it gives an introduction to how a \gls{GPU} might work, it specifically meantions how the Fermi architecture works and how it is possible to achieve parallarism.
I'm guessing it is mostly relevant because it shows a good example of how the GPU may also be used. The fermi architecture we can read about in manuals.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +There have been made a number of tools in order to make utilization of GPGU easier, these Higher Level GP\gls{GPU}'s tool includes the following: Firepile (Scala) \cite{2011_firepile}, OCaml GP\gls{G
Mention that these are only some of the avaliable tools and most of them are academic experimentations.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +These tools were made in order to make it easier and less error prone to utilize GP\gls{GPU} for less skilled developers. As it can be difficult to work with OpenCL and CUDA alone.
Why is it difficult to use OpenCL and CUDA?
Also OpenCL is mentioned out of the blue here.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +The value in these articles lies in how the developers exposed the lower level \gls{API}'s to a custom made higher level \gls{API}, and wheter or not they are user to use than their lower-level count
There's not really a standard for benchmarking either.
Give examples of how they test programmability and benchmarking. Otherwise we're just making statements.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +A critique of the paper though is that mege sort and radix sort starts to show strange performance spike patterns when working with large workload.
Is this important to us? 
Talk instead about the amount of throughput we get, is why GPGPU is interesting.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Designing efficient sorting algorithms for Manycore GPUs \cite{satish_2009_designing} is a article describes the development of a custom implemented radix and merge sort, and proove the capabilites o
Maybe place this before the section about higher-level APIs.
Thus we get a flow of "what is GPGPU" --> ""what throughput do we get" --> "how do we make it more avaliable"

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Debunking the 100x \gls{GPU} vs. CPU Myth \cite{lee_2010_debunking} claims that GP\gls{GPU}'s are not that much better than CPUs.
Maybe include this paper in the dicussion of Nivida instead as a counter point.
Right now it hangs out here all by itself ;(

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Let's Fix OpenGL \cite{fix_opengl} is a journal article that attempts to expose the shortcommings of OpenGL, and suggests what can be done in order to make OpenGL better.
If mentioning that it is a journal article. Maybe say where it was published?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +They communicate through commands written in the application, which is a very error-prone approach.
What do they communicate?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Everything must be explictly stated in the shader programs.
The title and the text don't quite fit.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +There are different tools for. Contributes to the issue of having to keep track of semantics depending on what kind of shader is being worked on.
Why is this important?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Let's Fix OpenGL  \cite{fix_opengl} identifies six issues:
In general, each of these points could be elaborated on.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Reducing Driver Overhead in OpenGL, Direct3D and Mantle  \cite{dobersberger_2015_reducing}
Isn't this also a comparison article?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +An Incremental Rendering VM \cite{haaser_2015_incremental}
This could be a nice double team with Claus's shader paper.
Combine them for a nice follow up to let's fix OpenGL.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +The value of this article is that it gives insight as to how a good graphics \gls{API} should work, it's good arguements to take into consideration when trying to evaluate an \gls{API}.
"The points brought up in this article may be valuable to keep in mind, when designing new graphics APIs".

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +There are several options in terms of what \gls{GPU} \gls{API} that can be used when a developer needs to render graphics in a application. This section discusses articles that compare \gls{GPU} \gls
Mention from the beginning that these are all master thesis. Say that academia haven't focused much on regular comparisons.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +In the conclusion the thesis states that Vulkan can give more throughput than OpenGL, although it is worth noting that the performance increase is dependent on what kind of hardware is used. Addition
Isn't it obivous that performance changes along with hardware?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +It only states that Vulkan is more difficult to work with than OpenGL because there is more overhead.
Overhead is more to do with performance.
It is instead more diffiuclt to work with as we are at a lower level of abstraction.

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +\paragraph{}
Do we need paragraphing?

2017-10-18 12:34 UTC, AlexanderBrandborg commented on mainmatter/introduction/related_work/index.tex
> +Aditionally there seems to be a lack on papers discussing DirectX12 and Vulkan(Besides the master thesis' there are none), and should therefor be considered a field that is worthwhile looking into.
Boom! This is what we like to see!

2017-10-18 12:34 UTC, TheVikingGent commented on mainmatter/introduction/related_work/index.tex
> +CUDA programs are very scalable according to the article, and is thus an excellent tool to utilize GP\gls{GPU} functionality, and encourages more ussage of GP\gls{GPU}. It is important to note that t
What is a framework tool?

2017-10-18 12:34 UTC, TheVikingGent commented on mainmatter/introduction/related_work/index.tex
> +Debunking the 100x \gls{GPU} vs. CPU Myth \cite{lee_2010_debunking} claims that GP\gls{GPU}'s are not that much better than CPUs.
Don't need to elaborate so much on it either. Just say that it's a counter point that says something different, but has the same kind of bias.

2017-10-18 12:34 UTC, TheVikingGent commented on mainmatter/introduction/related_work/index.tex
> +\paragraph 1 Programmers must juggle between C/C++ and HLSL and GLSL.
Bullets instead of paragraphs?

2017-10-18 13:12 UTC, NotKyloRen commented on mainmatter/introduction/related_work/index.tex
> +The second purpose for the \gls{GPU} is for rendering graphics, this is mostly used in video game software. The following sections will further explain the related works, and why they are relevant.
It shall be done

2017-10-19 10:06 UTC, AlexanderBrandborg approved these changes

2017-10-19 10:06 UTC, merged